#!/bin/bash
SYSLOG="/var/log"
LOG1="$SYSLOG/auth.log"
LOG2="$SYSLOG/auth.log.1"
LOG3="$SYSLOG/auth.log.2.gz"
LOG4="$SYSLOG/auth.log.3.gz"
LOG5="$SYSLOG/auth.log.4.gz"
session=""



get_len() {
    i=0
    for word in $1; do
        i=$((i+1))
    done 
    echo $i
}

get_time() {
    time=$(echo "$1" | cut -d " " -f 1)
    time=$(echo "$time" | cut -d "T" -f 2)
    time=$(echo "$time" | cut -d "." -f 1)

    echo "${time:0:5}"
}

get_date() {
    time=$(echo "$1" | cut -d " " -f 1)
    time=$(echo "$time" | cut -d "T" -f 1)

    echo $time
}

get_duration() {
    start=$1
    end=$2

    sm=$(echo "$start" | cut -d ":" -f 2)
    sh=$(echo "$start" | cut -d ":" -f 1)

    em=$(echo "$end" | cut -d ":" -f 2)
    eh=$(echo "$end" | cut -d ":" -f 1)


    h=$((10#$eh-10#$sh))
    m=$((10#$em-10#$sm))

    if [ $m -le -1 ]; then
        h=$(($h-1))
        m=$(($m+60))
    fi

    if [ $h -le -1 ]; then
        h=$(($h+24))
    fi

    echo "$h:$m"
}



mylast() {
    queue=""

    while read -r line; do
        if [ "$(echo $line | grep "systemd-logind")" ]; then  
            # User sucessful login
            if [ "$(echo $line | grep -i "new session")" ]; then  
                
                i=1
                while [ $i -le $(get_len "$line") ]; do
                    word=$(echo $line | cut -d " " -f $i)
 
                    if [ "$word" = "user" ]; then
                        user=$( echo $line | cut -d " " -f $((i+1)) )
                        user=$(echo $user | cut -d "." -f 1)

                        nsession=$( echo $line | cut -d " " -f $((i-2)) )

                        if [ "$user" != "lightdm" ]; then
                            #echo "added $user to the queue"
                            queue="$queue $user--$nsession--$(get_date "$line")--$(get_time "$line")"
                        fi
                    fi

                    i=$(($i+1)) 
                done

            fi
            
            # System power down
            if [ "$(echo $line | grep -i "system is powering down")" ]; then
                #echo "sys power down"
                #echo "updating entire queue"
                
                for user in $queue; do
                        duration=$(get_duration "$(echo "$user" | awk -F "--" '{print $4}')" "$(get_time "$line")")

                        session="$session \n $user-$(get_time "$line")--($duration)" # TODO  
                done
                queue=""
            fi
            
            # User session remove
            if [ "$(echo $line | grep -i "removed session")" ]; then
                queue_temp=""

                removed=$(echo $line | cut -d " " -f $(get_len "$line"))
                removed="${removed:0:2}"

                #echo "session removed $removed"
                #echo "updating queue"
                
                for user in $queue; do
                    if [ "$removed" = "$(echo $user | cut -d "-" -f 2)" ]; then
                        #echo -e "found user: $user to remove..."
                        duration=$(get_duration "$(echo "$user" | awk -F "--" '{print $4}')" "$(get_time "$line")")

                        session="$session \n $user-$(get_time "$line")--($duration)"
                    else 
                        queue_temp="$queue_temp $user"
                    fi      
                done
                queue=$queue_temp
            fi

            # Log out
            if [ "$(echo $line | grep -i "logged out")" ]; then
                queue_temp=""

                removed=$(echo $line | cut -d " " -f 5)
                removed="${removed:0:2}"

                #echo "session logged out $removed at $(get_time "$line")"
                #echo "updating queue"
                
                for user in $queue; do
                    if [ "$removed" = "$(echo $user | cut -d "-" -f 3)" ]; then
                        #echo -e "found user: $user to remove... "
                        duration=$(get_duration "$(echo "$user" | awk -F "--" '{print $4}')" "$(get_time "$line")")

                        session="$session \n $user-$(get_time "$line")--($duration)"
                    else 
                        queue_temp="$queue_temp $user"
                    fi      
                done
                queue=$queue_temp
            fi

        fi
    done <<< "$1"
    
    # Current sessions
    for user in $queue; do
            session="$session \n $user--(ongoing)" 
    done
    queue=""
}

mylastb() {
    while read -r line; do
        if [ "$(echo $line | grep -i "password check failed")" ]; then
            date="${line:0:10}"
            time="${line:11:5}"
            
            user=$(echo "$line" | cut -d "-" -f 3)
            user=$(echo "$user" | cut -d " " -f 2)

            session="$session \n $user--$date--$time"
        fi
    done <<< "$1"
}

n() {
    session="${session//"\n"/"  "}"

    i=$(get_len "$session")

    bottom=$(($i - $1 + 1))
    
    while [ $i -ge $bottom ]; do
        log=$(echo $session | cut -d " " -f $i)
        echo -e "${log//"--"/"  "}"
        
        i=$(($i-1))
    done
}   

s() {
    session="${session//"\n"/"  "}"

    for line in $session; do
        date=$(echo $line | awk -F "--" '{print $3}')
        time=$(echo $line | awk -F "--" '{print $4}')
        time=$(echo $time | awk -F "-" '{print $1}')
        datetime="$date-$time"
        datetime="${datetime//"-"/""}"
        datetime="${datetime//":"/""}"

        cutoff=$1
        cutoff="${cutoff//"-"/""}"
        
        if [ $datetime -ge $cutoff ]; then
            echo -e "${line//"--"/"  "}"
        fi
    done
}

t() {
    session="${session//"\n"/"  "}"

    for line in $session; do
        date=$(echo $line | awk -F "--" '{print $3}')
        time=$(echo $line | awk -F "--" '{print $4}')
        time=$(echo $time | awk -F "-" '{print $1}')
        datetime="$date-$time"
        datetime="${datetime//"-"/""}"
        datetime="${datetime//":"/""}"

        cutoff=$1
        cutoff="${cutoff//"-"/""}"
        
        if [ $datetime -le $cutoff ]; then
            echo -e "${line//"--"/"  "}"
        fi
    done
}

p() {
    session="${session//"\n"/"  "}"

    for line in $session; do
        date=$(echo $line | awk -F "--" '{print $3}')

        time=$(echo $line | awk -F "--" '{print $4}')
        time=$(echo $time | awk -F "-" '{print $1}')
        datetime="$date-$time"
        datetime="${datetime//"-"/""}"
        datetime="${datetime//":"/""}"

        present=$1
        present="${present//"-"/""}"

        endtime=$(echo $line | awk -F "--" '{print $4}')
        endtime=$(echo $endtime | awk -F "-" '{print $2}')
        enddatetime="$date-$endtime"
        enddatetime="${enddatetime//"-"/""}"
        enddatetime="${enddatetime//":"/""}"

        if [ $datetime -le $present ]; then
            if [ $enddatetime -ge $present ]; then
                echo -e "${line//"--"/"  "}"
            fi
        fi
    done
}



if [ "$1" = "-l" ]; then
    file="$(less $LOG5) $(less $LOG4) $(less $LOG3) $(cat $LOG2 $LOG1)"

    mylast "$file"
fi

if [ "$1" = "-lb" ]; then
    file="$(less $LOG5) $(less $LOG4) $(less $LOG3) $(cat $LOG2 $LOG1)"

    mylastb "$file"
fi

if [ "$2" = "-n" ]; then
    n "$3"
    exit 1
fi

if [ "$2" = "-p" ]; then
    p "$3"
    exit 1
fi

if [ "$2" = "-s" ]; then
    s "$3"
    exit 1
fi

if [ "$2" = "-t" ]; then
    t "$3"
    exit 1
fi

echo -e "${session//"--"/"  "}"
exit 1

